extension_dir="C:\Users\akshi\AppData\Local\Microsoft\WinGet\Packages\PHP.PHP.8.4_Microsoft.Winget.Source_8wekyb3d8bbwe\ext"

extension=curl
extension=fileinfo
extension=intl
extension=mbstring
extension=openssl
extension=pdo_pgsql
extension=pgsql
extension=zip

date.timezone=America/Argentina/Buenos_Aires
memory_limit=512M
upload_max_filesize=20M
post_max_size=25M
